# Screen dimensions
SCREEN_WIDTH = 720
SCREEN_HEIGHT = 850

# Board dimensions
ROWS = 10
COLS = 9

SQUARE_SIZE = 80

# Board width and height
BOARD_WIDTH = SQUARE_SIZE*(COLS - 1)
BOARD_HEIGHT = SQUARE_SIZE*(ROWS - 1)

# Offsets
BOARD_OFFSET_X = (SCREEN_WIDTH - BOARD_WIDTH)//2
BOARD_OFFSET_Y = (SCREEN_HEIGHT - BOARD_HEIGHT)//2

BG_COLOR = (235, 209, 166)
LINE_COLOR = (0, 0, 0)
RED_COLOR = (255, 0, 0)
BLACK_COLOR =(0, 0, 0)

RED = 1
BLACK = -1

MAX_TURN=2000

STEP_DELAY=500
SMOOTH_DELAY=10